version: "3"

services:
  rails-test-app:
    build: ./rails-test
    image: rails-on-minikube_rails-test-app:v1
    volumes:
    - ./rails-test:/app
    ports:
    - '8000:8000'
    env_file:
    - ./config/.rails-test.env
