apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: rails-test-app
  name: rails-test-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rails-test-app
    spec:
      containers:
      - env:
        - name: LISTEN_ON
          value: 0.0.0.0:8000
        - name: WORKER_PROCESSES
          value: "1"
        image: play_rails-test-app:v1
        name: rails-test-app
        ports:
        - containerPort: 8000
        resources: {}
      restartPolicy: Always
status: {}
